"""
Comprehensive Hospital Medical Data
Contains 50+ patients, conditions, medications, symptoms, treatments, lab tests
and all relationships for the medical knowledge graph
"""

HOSPITAL_DATA = {
    "patients": [
        {"patient_id": "P001", "name": "John Smith", "age": 65, "gender": "M", "blood_type": "O+", "admission_date": "2024-01-15"},
        {"patient_id": "P002", "name": "Sarah Johnson", "age": 58, "gender": "F", "blood_type": "A+", "admission_date": "2024-01-16"},
        {"patient_id": "P003", "name": "Michael Brown", "age": 72, "gender": "M", "blood_type": "B+", "admission_date": "2024-01-17"},
        {"patient_id": "P004", "name": "Emily Davis", "age": 45, "gender": "F", "blood_type": "AB+", "admission_date": "2024-01-18"},
        {"patient_id": "P005", "name": "Robert Wilson", "age": 68, "gender": "M", "blood_type": "O-", "admission_date": "2024-01-19"},
        {"patient_id": "P006", "name": "Jennifer Martinez", "age": 52, "gender": "F", "blood_type": "A+", "admission_date": "2024-01-20"},
        {"patient_id": "P007", "name": "David Anderson", "age": 61, "gender": "M", "blood_type": "B+", "admission_date": "2024-01-21"},
        {"patient_id": "P008", "name": "Lisa Taylor", "age": 55, "gender": "F", "blood_type": "O+", "admission_date": "2024-01-22"},
        {"patient_id": "P009", "name": "James Thomas", "age": 70, "gender": "M", "blood_type": "AB-", "admission_date": "2024-01-23"},
        {"patient_id": "P010", "name": "Patricia Jackson", "age": 48, "gender": "F", "blood_type": "A+", "admission_date": "2024-01-24"},
        {"patient_id": "P011", "name": "Christopher White", "age": 64, "gender": "M", "blood_type": "O+", "admission_date": "2024-01-25"},
        {"patient_id": "P012", "name": "Mary Harris", "age": 59, "gender": "F", "blood_type": "B+", "admission_date": "2024-01-26"},
        {"patient_id": "P013", "name": "Daniel Martin", "age": 66, "gender": "M", "blood_type": "A+", "admission_date": "2024-01-27"},
        {"patient_id": "P014", "name": "Barbara Thompson", "age": 71, "gender": "F", "blood_type": "O+", "admission_date": "2024-01-28"},
        {"patient_id": "P015", "name": "Matthew Garcia", "age": 53, "gender": "M", "blood_type": "AB+", "admission_date": "2024-01-29"},
        {"patient_id": "P016", "name": "Susan Lee", "age": 60, "gender": "F", "blood_type": "A+", "admission_date": "2024-01-30"},
        {"patient_id": "P017", "name": "Anthony Rodriguez", "age": 67, "gender": "M", "blood_type": "B+", "admission_date": "2024-02-01"},
        {"patient_id": "P018", "name": "Karen Clark", "age": 54, "gender": "F", "blood_type": "O+", "admission_date": "2024-02-02"},
        {"patient_id": "P019", "name": "Mark Lewis", "age": 69, "gender": "M", "blood_type": "A+", "admission_date": "2024-02-03"},
        {"patient_id": "P020", "name": "Nancy Walker", "age": 62, "gender": "F", "blood_type": "B+", "admission_date": "2024-02-04"},
        {"patient_id": "P021", "name": "Steven Hall", "age": 75, "gender": "M", "blood_type": "O+", "admission_date": "2024-02-05"},
        {"patient_id": "P022", "name": "Betty Allen", "age": 57, "gender": "F", "blood_type": "AB+", "admission_date": "2024-02-06"},
        {"patient_id": "P023", "name": "Paul Young", "age": 63, "gender": "M", "blood_type": "A+", "admission_date": "2024-02-07"},
        {"patient_id": "P024", "name": "Dorothy King", "age": 68, "gender": "F", "blood_type": "B+", "admission_date": "2024-02-08"},
        {"patient_id": "P025", "name": "Andrew Wright", "age": 56, "gender": "M", "blood_type": "O+", "admission_date": "2024-02-09"},
    ],
    
    "conditions": [
        {"condition_id": "COND001", "name": "Type 2 Diabetes", "severity": "High", "icd_code": "E11", "description": "Chronic metabolic disorder affecting blood glucose levels"},
        {"condition_id": "COND002", "name": "Hypertension", "severity": "High", "icd_code": "I10", "description": "Elevated blood pressure condition"},
        {"condition_id": "COND003", "name": "Asthma", "severity": "Medium", "icd_code": "J45", "description": "Chronic respiratory disorder"},
        {"condition_id": "COND004", "name": "Coronary Artery Disease", "severity": "Critical", "icd_code": "I25", "description": "Narrowing of arteries due to plaque buildup"},
        {"condition_id": "COND005", "name": "Chronic Obstructive Pulmonary Disease", "severity": "High", "icd_code": "J44", "description": "Progressive lung disease"},
        {"condition_id": "COND006", "name": "Heart Failure", "severity": "Critical", "icd_code": "I50", "description": "Heart unable to pump sufficient blood"},
        {"condition_id": "COND007", "name": "Atrial Fibrillation", "severity": "High", "icd_code": "I48", "description": "Irregular heart rhythm"},
        {"condition_id": "COND008", "name": "Chronic Kidney Disease", "severity": "High", "icd_code": "N18", "description": "Progressive loss of kidney function"},
        {"condition_id": "COND009", "name": "Osteoarthritis", "severity": "Medium", "icd_code": "M19", "description": "Degenerative joint disease"},
        {"condition_id": "COND010", "name": "Rheumatoid Arthritis", "severity": "Medium", "icd_code": "M05", "description": "Autoimmune inflammatory joint disease"},
        {"condition_id": "COND011", "name": "Hyperlipidemia", "severity": "Medium", "icd_code": "E78", "description": "High cholesterol levels"},
        {"condition_id": "COND012", "name": "Obesity", "severity": "Medium", "icd_code": "E66", "description": "Excessive body weight"},
        {"condition_id": "COND013", "name": "Depression", "severity": "Medium", "icd_code": "F32", "description": "Mental health disorder"},
        {"condition_id": "COND014", "name": "Anxiety Disorder", "severity": "Low", "icd_code": "F41", "description": "Excessive worry and fear"},
        {"condition_id": "COND015", "name": "Gastroesophageal Reflux Disease", "severity": "Low", "icd_code": "K21", "description": "Acid reflux condition"},
        {"condition_id": "COND016", "name": "Hypothyroidism", "severity": "Medium", "icd_code": "E03", "description": "Underactive thyroid gland"},
        {"condition_id": "COND017", "name": "Hyperthyroidism", "severity": "Medium", "icd_code": "E05", "description": "Overactive thyroid gland"},
        {"condition_id": "COND018", "name": "Migraine", "severity": "Low", "icd_code": "G43", "description": "Severe headache disorder"},
        {"condition_id": "COND019", "name": "Sleep Apnea", "severity": "High", "icd_code": "G47", "description": "Breathing interruptions during sleep"},
        {"condition_id": "COND020", "name": "Pneumonia", "severity": "High", "icd_code": "J18", "description": "Lung infection"},
    ],
    
    "medications": [
        {"medication_id": "MED001", "name": "Metformin", "dosage": "500mg", "frequency": "Twice daily", "category": "Antidiabetic"},
        {"medication_id": "MED002", "name": "Lisinopril", "dosage": "10mg", "frequency": "Once daily", "category": "ACE Inhibitor"},
        {"medication_id": "MED003", "name": "Albuterol", "dosage": "100mcg", "frequency": "As needed", "category": "Bronchodilator"},
        {"medication_id": "MED004", "name": "Atorvastatin", "dosage": "20mg", "frequency": "Once daily", "category": "Statin"},
        {"medication_id": "MED005", "name": "Amlodipine", "dosage": "5mg", "frequency": "Once daily", "category": "Calcium Channel Blocker"},
        {"medication_id": "MED006", "name": "Aspirin", "dosage": "81mg", "frequency": "Once daily", "category": "Antiplatelet"},
        {"medication_id": "MED007", "name": "Warfarin", "dosage": "5mg", "frequency": "Once daily", "category": "Anticoagulant"},
        {"medication_id": "MED008", "name": "Omeprazole", "dosage": "20mg", "frequency": "Once daily", "category": "Proton Pump Inhibitor"},
        {"medication_id": "MED009", "name": "Levothyroxine", "dosage": "75mcg", "frequency": "Once daily", "category": "Thyroid Hormone"},
        {"medication_id": "MED010", "name": "Sertraline", "dosage": "50mg", "frequency": "Once daily", "category": "SSRI"},
        {"medication_id": "MED011", "name": "Ibuprofen", "dosage": "400mg", "frequency": "Three times daily", "category": "NSAID"},
        {"medication_id": "MED012", "name": "Furosemide", "dosage": "40mg", "frequency": "Once daily", "category": "Diuretic"},
        {"medication_id": "MED013", "name": "Metoprolol", "dosage": "50mg", "frequency": "Twice daily", "category": "Beta Blocker"},
        {"medication_id": "MED014", "name": "Insulin Glargine", "dosage": "20 units", "frequency": "Once daily", "category": "Insulin"},
        {"medication_id": "MED015", "name": "Amoxicillin", "dosage": "500mg", "frequency": "Three times daily", "category": "Antibiotic"},
    ],
    
    "symptoms": [
        {"symptom_id": "SYM001", "name": "Fatigue", "severity": "Medium", "description": "Persistent tiredness and lack of energy"},
        {"symptom_id": "SYM002", "name": "Chest Pain", "severity": "High", "description": "Discomfort or pain in the chest area"},
        {"symptom_id": "SYM003", "name": "Shortness of Breath", "severity": "High", "description": "Difficulty breathing or feeling out of breath"},
        {"symptom_id": "SYM004", "name": "Frequent Urination", "severity": "Low", "description": "Need to urinate more frequently than normal"},
        {"symptom_id": "SYM005", "name": "Excessive Thirst", "severity": "Low", "description": "Increased thirst and dry mouth"},
        {"symptom_id": "SYM006", "name": "Headache", "severity": "Low", "description": "Pain or pressure in the head"},
        {"symptom_id": "SYM007", "name": "Dizziness", "severity": "Medium", "description": "Feeling lightheaded or vertigo"},
        {"symptom_id": "SYM008", "name": "Nausea", "severity": "Medium", "description": "Feeling sick or queasy"},
        {"symptom_id": "SYM009", "name": "Cough", "severity": "Medium", "description": "Persistent coughing"},
        {"symptom_id": "SYM010", "name": "Fever", "severity": "High", "description": "Elevated body temperature"},
        {"symptom_id": "SYM011", "name": "Joint Pain", "severity": "Medium", "description": "Pain in joints"},
        {"symptom_id": "SYM012", "name": "Muscle Weakness", "severity": "Medium", "description": "Loss of muscle strength"},
        {"symptom_id": "SYM013", "name": "Swelling", "severity": "Medium", "description": "Edema or puffiness"},
        {"symptom_id": "SYM014", "name": "Insomnia", "severity": "Low", "description": "Difficulty sleeping"},
        {"symptom_id": "SYM015", "name": "Anxiety", "severity": "Low", "description": "Excessive worry or nervousness"},
    ],
    
    "treatments": [
        {"treatment_id": "TREAT001", "name": "Coronary Angioplasty", "type": "Surgical", "duration_days": 1, "description": "Procedure to open blocked arteries"},
        {"treatment_id": "TREAT002", "name": "Bypass Surgery", "type": "Surgical", "duration_days": 5, "description": "Surgical creation of alternative blood vessel pathway"},
        {"treatment_id": "TREAT003", "name": "Dialysis", "type": "Therapeutic", "duration_days": 180, "description": "Artificial kidney treatment"},
        {"treatment_id": "TREAT004", "name": "Physical Therapy", "type": "Rehabilitation", "duration_days": 30, "description": "Exercise and movement therapy"},
        {"treatment_id": "TREAT005", "name": "Pulmonary Rehabilitation", "type": "Rehabilitation", "duration_days": 60, "description": "Breathing and exercise training"},
        {"treatment_id": "TREAT006", "name": "Cardiac Rehabilitation", "type": "Rehabilitation", "duration_days": 45, "description": "Heart recovery program"},
        {"treatment_id": "TREAT007", "name": "Chemotherapy", "type": "Medical", "duration_days": 180, "description": "Cancer treatment with drugs"},
        {"treatment_id": "TREAT008", "name": "Radiation Therapy", "type": "Medical", "duration_days": 42, "description": "Cancer treatment with radiation"},
        {"treatment_id": "TREAT009", "name": "Cognitive Behavioral Therapy", "type": "Psychological", "duration_days": 90, "description": "Mental health treatment"},
        {"treatment_id": "TREAT010", "name": "Joint Replacement", "type": "Surgical", "duration_days": 3, "description": "Replacement of damaged joint"},
    ],
    
    "lab_tests": [
        {"test_id": "LAB001", "name": "Complete Blood Count", "code": "CBC", "normal_range": "4.5-11.0 K/uL", "unit": "K/uL"},
        {"test_id": "LAB002", "name": "Fasting Blood Glucose", "code": "FBG", "normal_range": "70-100 mg/dL", "unit": "mg/dL"},
        {"test_id": "LAB003", "name": "Hemoglobin A1C", "code": "HbA1C", "normal_range": "<5.7%", "unit": "%"},
        {"test_id": "LAB004", "name": "Total Cholesterol", "code": "TC", "normal_range": "<200 mg/dL", "unit": "mg/dL"},
        {"test_id": "LAB005", "name": "LDL Cholesterol", "code": "LDL", "normal_range": "<100 mg/dL", "unit": "mg/dL"},
        {"test_id": "LAB006", "name": "HDL Cholesterol", "code": "HDL", "normal_range": ">40 mg/dL", "unit": "mg/dL"},
        {"test_id": "LAB007", "name": "Triglycerides", "code": "TG", "normal_range": "<150 mg/dL", "unit": "mg/dL"},
        {"test_id": "LAB008", "name": "Creatinine", "code": "Cr", "normal_range": "0.7-1.3 mg/dL", "unit": "mg/dL"},
        {"test_id": "LAB009", "name": "Blood Urea Nitrogen", "code": "BUN", "normal_range": "7-20 mg/dL", "unit": "mg/dL"},
        {"test_id": "LAB010", "name": "Thyroid Stimulating Hormone", "code": "TSH", "normal_range": "0.4-4.0 mIU/L", "unit": "mIU/L"},
        {"test_id": "LAB011", "name": "Troponin", "code": "Tn", "normal_range": "<0.04 ng/mL", "unit": "ng/mL"},
        {"test_id": "LAB012", "name": "B-type Natriuretic Peptide", "code": "BNP", "normal_range": "<100 pg/mL", "unit": "pg/mL"},
        {"test_id": "LAB013", "name": "Liver Function Test", "code": "LFT", "normal_range": "Varies", "unit": "U/L"},
        {"test_id": "LAB014", "name": "Prothrombin Time", "code": "PT", "normal_range": "11-13.5 seconds", "unit": "seconds"},
        {"test_id": "LAB015", "name": "Activated Partial Thromboplastin Time", "code": "aPTT", "normal_range": "25-35 seconds", "unit": "seconds"},
    ],
    
    "risk_factors": [
        {"risk_factor_id": "RF001", "name": "Smoking", "category": "Lifestyle", "description": "Active or passive smoking increases multiple health risks"},
        {"risk_factor_id": "RF002", "name": "Obesity", "category": "Lifestyle", "description": "Excess body weight increases disease risk"},
        {"risk_factor_id": "RF003", "name": "Sedentary Lifestyle", "category": "Lifestyle", "description": "Lack of physical activity increases disease risk"},
        {"risk_factor_id": "RF004", "name": "Poor Diet", "category": "Lifestyle", "description": "High sodium, sugar, and fat intake"},
        {"risk_factor_id": "RF005", "name": "Excessive Alcohol", "category": "Lifestyle", "description": "Heavy alcohol consumption"},
        {"risk_factor_id": "RF006", "name": "Family History", "category": "Genetic", "description": "Hereditary predisposition to disease"},
        {"risk_factor_id": "RF007", "name": "Age", "category": "Demographic", "description": "Advanced age increases risk"},
        {"risk_factor_id": "RF008", "name": "Stress", "category": "Psychological", "description": "Chronic stress and anxiety"},
        {"risk_factor_id": "RF009", "name": "Sleep Deprivation", "category": "Lifestyle", "description": "Insufficient sleep"},
        {"risk_factor_id": "RF010", "name": "Environmental Pollution", "category": "Environmental", "description": "Air and water pollution exposure"},
    ],
    
    "preventions": [
        {"prevention_id": "PRV001", "name": "Regular Exercise", "category": "Physical", "description": "150 minutes of moderate activity per week"},
        {"prevention_id": "PRV002", "name": "Healthy Diet", "category": "Nutritional", "description": "Balanced nutrition with reduced sodium and sugar"},
        {"prevention_id": "PRV003", "name": "Regular Health Checkups", "category": "Screening", "description": "Annual or bi-annual medical examinations"},
        {"prevention_id": "PRV004", "name": "Smoking Cessation", "category": "Behavioral", "description": "Quit smoking programs"},
        {"prevention_id": "PRV005", "name": "Weight Management", "category": "Physical", "description": "Maintain healthy body weight"},
        {"prevention_id": "PRV006", "name": "Stress Management", "category": "Psychological", "description": "Meditation and relaxation techniques"},
        {"prevention_id": "PRV007", "name": "Vaccination", "category": "Preventive", "description": "Immunization against diseases"},
        {"prevention_id": "PRV008", "name": "Limit Alcohol", "category": "Behavioral", "description": "Moderate alcohol consumption"},
        {"prevention_id": "PRV009", "name": "Sleep Hygiene", "category": "Behavioral", "description": "7-9 hours of quality sleep"},
        {"prevention_id": "PRV010", "name": "Blood Pressure Monitoring", "category": "Screening", "description": "Regular BP checks"},
    ],
    
    "patient_condition_relationships": [
        ("P001", "COND001", "2023-01-15", "active"),
        ("P001", "COND002", "2022-06-20", "active"),
        ("P001", "COND011", "2023-03-10", "active"),
        ("P002", "COND002", "2021-11-05", "active"),
        ("P002", "COND004", "2023-06-15", "active"),
        ("P003", "COND005", "2020-08-12", "active"),
        ("P003", "COND003", "2022-02-28", "active"),
        ("P004", "COND009", "2023-01-20", "active"),
        ("P004", "COND013", "2023-04-10", "active"),
        ("P005", "COND006", "2023-02-14", "active"),
        ("P005", "COND007", "2022-09-30", "active"),
        ("P006", "COND008", "2021-05-22", "active"),
        ("P006", "COND002", "2023-01-10", "active"),
        ("P007", "COND001", "2022-12-01", "active"),
        ("P007", "COND011", "2023-02-15", "active"),
        ("P008", "COND003", "2023-03-05", "active"),
        ("P008", "COND015", "2023-01-25", "active"),
        ("P009", "COND004", "2022-07-18", "active"),
        ("P009", "COND002", "2021-10-12", "active"),
        ("P010", "COND010", "2023-02-20", "active"),
        ("P011", "COND001", "2023-01-30", "active"),
        ("P012", "COND002", "2022-11-15", "active"),
        ("P013", "COND005", "2021-09-08", "active"),
        ("P014", "COND006", "2023-01-05", "active"),
        ("P015", "COND001", "2023-02-10", "active"),
        ("P016", "COND016", "2022-08-20", "active"),
        ("P017", "COND002", "2023-01-12", "active"),
        ("P018", "COND003", "2023-03-15", "active"),
        ("P019", "COND004", "2022-10-25", "active"),
        ("P020", "COND001", "2023-02-28", "active"),
    ],
    
    "condition_symptom_relationships": [
        ("COND001", "SYM004", "commonly presents with"),
        ("COND001", "SYM005", "commonly presents with"),
        ("COND001", "SYM001", "may cause"),
        ("COND002", "SYM006", "may cause"),
        ("COND002", "SYM007", "may cause"),
        ("COND003", "SYM003", "causes"),
        ("COND003", "SYM009", "causes"),
        ("COND004", "SYM002", "primary symptom"),
        ("COND004", "SYM003", "causes"),
        ("COND005", "SYM003", "causes"),
        ("COND005", "SYM009", "causes"),
        ("COND006", "SYM002", "primary symptom"),
        ("COND006", "SYM003", "causes"),
        ("COND006", "SYM001", "causes"),
        ("COND007", "SYM007", "may cause"),
        ("COND008", "SYM001", "causes"),
        ("COND009", "SYM011", "primary symptom"),
        ("COND010", "SYM011", "primary symptom"),
        ("COND011", "SYM001", "may cause"),
        ("COND013", "SYM001", "causes"),
        ("COND013", "SYM014", "causes"),
        ("COND014", "SYM015", "primary symptom"),
        ("COND015", "SYM008", "causes"),
        ("COND018", "SYM006", "primary symptom"),
        ("COND019", "SYM001", "causes"),
        ("COND020", "SYM010", "causes"),
    ],
    
    "medication_condition_relationships": [
        ("MED001", "COND001", "treats"),
        ("MED002", "COND002", "treats"),
        ("MED003", "COND003", "treats"),
        ("MED004", "COND011", "treats"),
        ("MED005", "COND002", "treats"),
        ("MED006", "COND004", "treats"),
        ("MED007", "COND007", "treats"),
        ("MED008", "COND015", "treats"),
        ("MED009", "COND016", "treats"),
        ("MED010", "COND013", "treats"),
        ("MED011", "COND009", "treats"),
        ("MED012", "COND006", "treats"),
        ("MED013", "COND002", "treats"),
        ("MED014", "COND001", "treats"),
        ("MED015", "COND020", "treats"),
    ],
    
    "condition_complication_relationships": [
        ("COND001", "COND002", "can lead to"),
        ("COND001", "COND004", "can lead to"),
        ("COND001", "COND008", "can lead to"),
        ("COND002", "COND004", "can lead to"),
        ("COND002", "COND006", "can lead to"),
        ("COND003", "COND005", "can lead to"),
        ("COND004", "COND006", "can lead to"),
        ("COND005", "COND006", "can lead to"),
        ("COND006", "COND007", "can lead to"),
        ("COND008", "COND006", "can lead to"),
    ],
}
